# --- Setup
title:            MyStreet 2
tagline:          '(c) 2018 SFCTA'
description:      'Project explorer'
url:              'http://mystreet.sfcta.org'
baseurl:          /
version:          0.0.1

author:
  name:           'SFCTA Staff'
  url:            http://www.sfcta.org

# --- Permalinks
permalink:        pretty
relative_permalinks: false

github:
  repo:           git@github.com:sfcta/mystreet2.git

# --- Build settings
source: src
destination: _site
exclude: ['node_modules']
plugins:
  - jekyll-sitemap
page_gen:
  - data: 'projects'
    template: 'projectpage'
    name: 'project_number'
    dir: 'project'
    index_files: true
